name: Deployment Pipeline

on:
  push:
    branches: 
      - main

jobs:
  deply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Limpiar e instalar dependencias
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund
      - name: Lint
        run: npm run eslint
      - name: Test
        run: npm run test
  

      
